PUT http://localhost:8080/events/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlMkBnbWFpbC5jb20iLCJleHAiOjE3MDkyNTcwMDcsInVzZXJJZCI6Mn0.ttImWWVBVJBLF6wps-ATIvqaA_-2lNw-1x_x68337N4

{
    "name": "evento legal modificada",
    "description": "apenas para os legais!",
    "location": "SC",
    "dateTime": "2015-01-01T:15:30:00.000Z"
}